"""empty message

Revision ID: 587a03ea50a6
Revises: 2898650c7d3e
Create Date: 2020-12-09 16:41:40.535508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587a03ea50a6'
down_revision = '2898650c7d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
